// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace saleseeker_data
{
    // NotificationSent
    public class NotificationSent
    {
        public int NotificationSentId { get; set; } // NotificationSentID (Primary key)
        public int UserId { get; set; } // UserID
        public DateTime SentDateTIme { get; set; } // SentDateTIme
        public string SentAddress { get; set; } // SentAddress (length: 100)
        public int ScrapedItemId { get; set; } // ScrapedItemID
        public decimal NotifiedPrice { get; set; } // NotifiedPrice

        // Foreign keys

        /// <summary>
        /// Parent ScrapedItem pointed by [NotificationSent].([ScrapedItemId]) (FK_NotificationSent_ScrapedItem)
        /// </summary>
        public virtual ScrapedItem ScrapedItem { get; set; } // FK_NotificationSent_ScrapedItem

        /// <summary>
        /// Parent SubscribedUser pointed by [NotificationSent].([UserId]) (FK_NotificationSent_SubscribedUser)
        /// </summary>
        public virtual SubscribedUser SubscribedUser { get; set; } // FK_NotificationSent_SubscribedUser
    }

}
// </auto-generated>
