// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace polei_data
{
    // ScrapedItem
    public class ScrapedItem
    {
        public int ScrapedItemId { get; set; } // ScrapedItemID (Primary key)
        public int SiteItemId { get; set; } // SiteItemID
        public decimal PriceIncVat { get; set; } // PriceIncVAT
        public decimal? PriceExVat { get; set; } // PriceExVAT
        public DateTime ScrapedDateTime { get; set; } // ScrapedDateTime

        // Reverse navigation

        /// <summary>
        /// Child NotificationSents where [NotificationSent].[ScrapedItemID] point to this entity (FK_NotificationSent_ScrapedItem)
        /// </summary>
        public virtual ICollection<NotificationSent> NotificationSents { get; set; } // NotificationSent.FK_NotificationSent_ScrapedItem

        // Foreign keys

        /// <summary>
        /// Parent SiteItem pointed by [ScrapedItem].([SiteItemId]) (FK_ScrapedItem_SiteItem)
        /// </summary>
        public virtual SiteItem SiteItem { get; set; } // FK_ScrapedItem_SiteItem

        public ScrapedItem()
        {
            NotificationSents = new List<NotificationSent>();
        }
    }

}
// </auto-generated>
