// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace polei_data
{
    // SubscribedUser
    public class SubscribedUser
    {
        public int UserId { get; set; } // UserID (Primary key)
        public string EmailAddress { get; set; } // EmailAddress (length: 100)
        public string FirstName { get; set; } // FirstName (length: 100)
        public string Surname { get; set; } // Surname (length: 100)
        public DateTime SubscribedDate { get; set; } // SubscribedDate
        public DateTime? VerifiedDate { get; set; } // VerifiedDate
        public string CellNumber { get; set; } // CellNumber (length: 20)

        // Reverse navigation

        /// <summary>
        /// Child NotificationSents where [NotificationSent].[UserID] point to this entity (FK_NotificationSent_SubscribedUser)
        /// </summary>
        public virtual ICollection<NotificationSent> NotificationSents { get; set; } // NotificationSent.FK_NotificationSent_SubscribedUser

        /// <summary>
        /// Child SubscribedItems where [SubscribedItem].[UserID] point to this entity (FK_SubscribedItem_SubscribedUser)
        /// </summary>
        public virtual ICollection<SubscribedItem> SubscribedItems { get; set; } // SubscribedItem.FK_SubscribedItem_SubscribedUser

        public SubscribedUser()
        {
            NotificationSents = new List<NotificationSent>();
            SubscribedItems = new List<SubscribedItem>();
        }
    }

}
// </auto-generated>
