// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace saleseeker_data
{
    // ItemType
    public class ItemType
    {
        public int ItemTypeId { get; set; } // ItemTypeID (Primary key)
        public string ItemTypeName { get; set; } // ItemTypeName (length: 30)

        // Reverse navigation

        /// <summary>
        /// Child Packs where [Pack].[ItemTypeID] point to this entity (FK_Pack_ItemType)
        /// </summary>
        public virtual ICollection<Pack> Packs { get; set; } // Pack.FK_Pack_ItemType

        public ItemType()
        {
            Packs = new List<Pack>();
        }
    }

}
// </auto-generated>
