// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace saleseeker_data
{
    // SubscribedItem
    public class SubscribedItem
    {
        public int SubscribedItemId { get; set; } // SubscribedItemID (Primary key)
        public int UserId { get; set; } // UserID
        public int ItemId { get; set; } // ItemID
        public int? SiteId { get; set; } // SiteID
        public decimal? BasePrice { get; set; } // BasePrice
        public int? PercentDiscount { get; set; } // PercentDiscount
        public decimal NotificationThreshold { get; set; } // NotificationThreshold

        // Foreign keys

        /// <summary>
        /// Parent Item pointed by [SubscribedItem].([ItemId]) (FK_SubscribedItem_Item)
        /// </summary>
        public virtual Item Item { get; set; } // FK_SubscribedItem_Item

        /// <summary>
        /// Parent Site pointed by [SubscribedItem].([SiteId]) (FK_SubscribedItem_Site)
        /// </summary>
        public virtual Site Site { get; set; } // FK_SubscribedItem_Site

        /// <summary>
        /// Parent SubscribedUser pointed by [SubscribedItem].([UserId]) (FK_SubscribedItem_SubscribedUser)
        /// </summary>
        public virtual SubscribedUser SubscribedUser { get; set; } // FK_SubscribedItem_SubscribedUser
    }

}
// </auto-generated>
