// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace polei_data
{
    // ItemType
    public class ItemTypeConfiguration : IEntityTypeConfiguration<ItemType>
    {
        public void Configure(EntityTypeBuilder<ItemType> builder)
        {
            builder.ToTable("ItemType", "dbo");
            builder.HasKey(x => x.ItemTypeId).HasName("PK_ItemType").IsClustered();

            builder.Property(x => x.ItemTypeId).HasColumnName(@"ItemTypeID").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.ItemTypeName).HasColumnName(@"ItemTypeName").HasColumnType("varchar(30)").IsRequired().IsUnicode(false).HasMaxLength(30);
        }
    }

}
// </auto-generated>
