// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace polei_data
{
    // SubscribedItem
    public class SubscribedItemConfiguration : IEntityTypeConfiguration<SubscribedItem>
    {
        public void Configure(EntityTypeBuilder<SubscribedItem> builder)
        {
            builder.ToTable("SubscribedItem", "dbo");
            builder.HasKey(x => x.SubscribedItemId).HasName("PK_SubscribedItem").IsClustered();

            builder.Property(x => x.SubscribedItemId).HasColumnName(@"SubscribedItemID").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.UserId).HasColumnName(@"UserID").HasColumnType("int").IsRequired();
            builder.Property(x => x.ItemId).HasColumnName(@"ItemID").HasColumnType("int").IsRequired();
            builder.Property(x => x.SiteId).HasColumnName(@"SiteID").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.BasePrice).HasColumnName(@"BasePrice").HasColumnType("numeric(10,2)").HasPrecision(10,2).IsRequired(false);
            builder.Property(x => x.PercentDiscount).HasColumnName(@"PercentDiscount").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.NotificationThreshold).HasColumnName(@"NotificationThreshold").HasColumnType("numeric(10,2)").HasPrecision(10,2).IsRequired();

            // Foreign keys
            builder.HasOne(a => a.Item).WithMany(b => b.SubscribedItems).HasForeignKey(c => c.ItemId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_SubscribedItem_Item");
            builder.HasOne(a => a.Site).WithMany(b => b.SubscribedItems).HasForeignKey(c => c.SiteId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_SubscribedItem_Site");
            builder.HasOne(a => a.SubscribedUser).WithMany(b => b.SubscribedItems).HasForeignKey(c => c.UserId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_SubscribedItem_SubscribedUser");
        }
    }

}
// </auto-generated>
