// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore.Design;

namespace polei_data
{
    public class SSDbContextFactory : IDesignTimeDbContextFactory<SSDbContext>
    {
        public SSDbContext CreateDbContext(string[] args)
        {
            return new SSDbContext();
        }
    }
}
// </auto-generated>
